export const productCategories = [
    "Books",
    "Jewelry & Accessories",
    "Spiritual Oil",
    "Portions",
    "Yantras",
    "Talisman, Charms & Amulets",
    "Prayer Items",
    "Music and Vidoes",
    "Candles and Essences",
    "Gift Baskets",
    "Ritual Kits",
    "Charged Items",
    "Charms",
    "Status",
    "Meditation Items",
    "Stones, Crystals & Beads",
    "Tarot Card",
    "Runes",
    "Ritual Clothing",
    "Wonds",
    "Home Protections and Items",
    "Self Protection & Wealth Items",
    "Business Wealth Items",
    "Vehicle Protection Items",
    "Spells and Mantras",
    "Prayer Items & Accessories",
    "FENG SHUI Items",
    "Spiritual Bath & Body products",
    "Sound Therapy items",
    "Divination Items and Accessories",
    "Prayer room accessories decors",
    "Cleansing Items"
];

export const serviceCategories = [
    "Psychic Medium" ,
    "Palm leaf Reading" ,
    "Spiritual Healing" ,
    "Astrology Reading" ,
    "Fortune Teller" ,
    "Psychic Reading" ,
    "Hex Removal" ,
    "Black Magic" ,
    "White Magic" ,
    "3rd Eye",
    "Job Issues",
    "Clairvoyance", 
    "Healer", 
    "Prayer & Ritual Services", 
    "Tarot, Rune, leaf, crystal readers", 
    "Spellcaster", 
    "Cleansing Services", 
    "Karma Reading", 
    "Custom Yantra maker", 
    "Face Reading", 
    "Palmistry", 
    "Akashic records", 
    "Numerology", 
    "Meditation Techniques", 
    "Aura Reading & Therapy", 
    "Voodoo Services", 
    "Horoscopes", 
    "Relationship improvement", 
    "Business Support Services", 
    "Legal issues services", 
    "Health Problem Services", 
    "Family Issues services"
];